# -*- coding: utf-8 -*-
"""Ncert-MINI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2ohK0Gn4iptOPpiaE5SpnSdrwjAbyEx

I am able to chunk corectly also I am able to get the related answers but still unable to find the correct answers.
"""

!pip install PyMuPDF

!pip install rank_bm25

"""Next, let's define a function `extract_text_from_pdf` that takes a PDF file path as input and returns all the text extracted from it."""

import fitz # PyMuPDF

def extract_text_from_pdf(pdf_path):
    """
    Extracts all text from a given PDF file.

    Args:
        pdf_path (str): The path to the PDF file.

    Returns:
        str: The extracted text from the PDF, or an empty string if an error occurs.
    """
    try:
        doc = fitz.open(pdf_path)
        text = ""
        for page_num in range(12,doc.page_count):
            page = doc.load_page(page_num)
            text += page.get_text()
        doc.close()
        return text
    except Exception as e:
        print(f"Error processing PDF {pdf_path}: {e}")
        return ""

"""Now, let's use the `extract_text_from_pdf` function to extract text from the `ncert-9-1-30.pdf` file and display the first 500 characters."""

pdf_file_path = '/content/ncert-9-1-30.pdf'
extracted_text = extract_text_from_pdf(pdf_file_path)

if extracted_text:
    print(extracted_text[:500])  # Print the first 500 characters of the extracted text
    print(f"\nTotal characters extracted: {len(extracted_text)}")
else:
    print(f"Failed to extract text from {pdf_file_path}")

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from collections import Counter
import re
stop_words = set(stopwords.words('english'))

words = re.findall(r'\b\w+\b', extracted_text.lower())


# Filter out stop words from the 'words' list
filtered_words = [word for word in words if word not in stop_words]

# Recalculate word frequencies for the filtered list
filtered_counter = Counter(filtered_words)

print("Top 30 most common words after removing stop words:")
print(filtered_counter.most_common(30))

def check_keywords(keywords):
  for word in keywords:
    count = filtered_words.count(word.lower()) # Ensure keyword is lowercase for comparison
    print(f"{word} -> {count}")

example_keywords = [
    "example", "illustration", "illustrate", "illustrated",
    "worked example", "case", "case study", "sample"
]

check_keywords(example_keywords)

question_keywords = [
    "exercise", "question", "questions", "problem",
    "problems", "q.", "q", "exercises", "solve",
    "evaluate", "find", "calculate", "explain",
    "define", "derive", "state"
]

check_keywords(question_keywords)

concept_keywords = [
    "is defined as", "refers to", "means", "definition",
    "called", "known as", "states that", "can be defined as"
]

check_keywords(concept_keywords)

law_keywords = [
    "law", "theorem", "principle", "rule",
    "newton", "archimedes", "ohm", "boyle"
]
check_keywords(law_keywords)

formula_keywords = [
    "=", "+", "-", "*", "/", "^",
    "equation", "formula", "calculate",
    "where", "given", "thus"
]

check_keywords(formula_keywords)

#Adding basic cleaning
def clean_text(text):
    text = re.sub(r'\n+', '\n', text)          # remove extra newlines
    text = re.sub(r'\s+', ' ', text)           # normalize spaces
    return text.strip()

# def split_into_blocks(text):
#     raw_blocks = text.split("\n\n")
#     final_blocks = []

#     for block in raw_blocks:
#         block = block.strip()

#         if not block:
#             continue

#         if "exercise" in block.lower():
#             lines = block.split("\n")
#             for line in lines:
#                 if line.strip():
#                     final_blocks.append(line.strip())
#         else:
#             final_blocks.append(block)

#     return final_blocks

def split_into_blocks(text):
    blocks = text.split("\n\n")

    cleaned_blocks = []
    for b in blocks:
        b = b.strip()
        if len(b) > 20:   # remove noise
            cleaned_blocks.append(b)

    return cleaned_blocks

def is_boundary(line):
    line = line.strip()

    if not line:
        return False

    lower = line.lower()

    return (
        lower.startswith(("example", "illustration")) or
        lower.startswith(("exercise", "questions")) or
        lower.startswith(("q.", "q ")) or
        line.startswith(tuple(str(i) + "." for i in range(1, 20))) or
        (len(line) < 60 and line.isupper())
    )

def split_into_blocks(text):
    lines = text.split("\n")

    blocks = []
    current_block = ""

    for line in lines:
        line = line.strip()

        if not line:
            continue

        # 🚨 If boundary → close current block
        if is_boundary(line):
            if current_block:
                blocks.append(current_block.strip())
                current_block = ""

            blocks.append(line)  # boundary itself is a block

        else:
            # ✅ Merge lines into meaningful block
            if current_block:
                current_block += " " + line
            else:
                current_block = line

    if current_block:
        blocks.append(current_block.strip())

    return blocks

def classify_block(text):
    t = text.lower()

    # Question
    if text.strip().startswith(tuple(str(i) + "." for i in range(1, 20))):
        return "question"

    if any(k in t for k in ["question", "questions", "q"]):
        return "question"

    # Example
    if any(k in t for k in ["example", "illustration", "case", "sample"]):
        return "example"

    # Formula
    if "=" in text:
        return "formula"

    # Concept
    return "concept"

def build_structured_blocks(text):
    blocks = split_into_blocks(text)

    structured = []
    for b in blocks:
        structured.append({
            "text": b,
            "type": classify_block(b)
        })

    return structured

structured_blocks = build_structured_blocks(extracted_text)

for b in structured_blocks[10:50]:
    print("\nTYPE:", b["type"])
    print(b["text"])

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("t5-small")

def chunk_blocks_new(structured_blocks, chunk_size=25, overlap=10):
    chunks = []

    for block in structured_blocks:
        text = block["text"]
        block_type = block["type"]

        tokens = tokenizer.encode(text)

        if len(tokens) <= chunk_size:
            chunks.append({
                "text": text,
                "type": block_type
            })
            continue

        start = 0
        while start < len(tokens):
            end = start + chunk_size
            chunk_tokens = tokens[start:end]

            chunk_text = tokenizer.decode(chunk_tokens)

            chunks.append({
                "text": chunk_text,
                "type": block_type
            })

            start += chunk_size - overlap

    return chunks

tokenized_chunks = chunk_blocks_new(structured_blocks)

for c in tokenized_chunks[:5]:
    print("\nTYPE:", c["type"])
    print(c["text"])

from rank_bm25 import BM25Okapi

# Prepare BM25 corpus
corpus = [chunk["text"] for chunk in chunks]
tokenized_corpus = [doc.lower().split() for doc in corpus]

bm25 = BM25Okapi(tokenized_corpus)


def retrieve(query, top_k=3):
    tokenized_query = query.lower().split()
    scores = bm25.get_scores(tokenized_query)

    ranked_indices = sorted(
        range(len(scores)), key=lambda i: scores[i], reverse=True
    )

    return [chunks[i] for i in ranked_indices[:top_k]]

def build_prompt(query, retrieved_chunks):
    context = ""

    for i, chunk in enumerate(retrieved_chunks):
        context += f"[Chunk {i+1} | {chunk['type']}]\n{chunk['text']}\n\n"

    prompt = f"""
You are a science tutor. Answer ONLY from the given context.

If the answer is NOT present in the context, say:
"I don't know based on the provided content."

Context:
{context}

Question:
{query}

Answer:
"""

    return prompt

import google.generativeai as genai

genai.configure(api_key="YOUR_API_KEY")

model = genai.GenerativeModel("gemini-1.5-flash")


def generate_answer(prompt):
    response = model.generate_content(
        prompt,
        generation_config={
            "temperature": 0  # IMPORTANT for evaluation
        }
    )
    return response.text

def answer(question):
    retrieved_chunks = retrieve(question, top_k=3)

    prompt = build_prompt(question, retrieved_chunks)

    answer_text = generate_answer(prompt)

    return {
        "question": question,
        "answer": answer_text,
        "chunks": retrieved_chunks
    }

result = answer("What is force?")

print("QUESTION:", result["question"])
print("\nANSWER:", result["answer"])

print("\nRETRIEVED CHUNKS:")
for c in result["chunks"]:
    print("-", c["text"][:150])

from rank_bm25 import BM25Okapi

# 🔹 Step 1 — Prepare BM25 (run once)
def build_retriever(chunks):
    corpus = [chunk["text"] for chunk in chunks]
    tokenized_corpus = [doc.lower().split() for doc in corpus]

    bm25 = BM25Okapi(tokenized_corpus)

    return bm25, corpus


# 🔹 Step 2 — Retrieval function
def get_relevant_chunks(query, chunks, bm25, top_k=3):
    tokenized_query = query.lower().split()

    scores = bm25.get_scores(tokenized_query)

    ranked_indices = sorted(
        range(len(scores)), key=lambda i: scores[i], reverse=True
    )

    results = []
    for idx in ranked_indices[:top_k]:
        results.append({
            "text": chunks[idx]["text"],
            "type": chunks[idx]["type"],
            "score": scores[idx]
        })

    return results

# Build retriever (once)
bm25, corpus = build_retriever(tokenized_chunks)

# Query
results = get_relevant_chunks("Define motion", tokenized_chunks, bm25, top_k=3)

for r in results:
    print("\nTYPE:", r["type"])
    print("SCORE:", r["score"])
    print("TEXT:", r["text"][:200])