# -*- coding: utf-8 -*-
"""Ncert-MINI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2ohK0Gn4iptOPpiaE5SpnSdrwjAbyEx
"""



!pip install PyMuPDF

"""Next, let's define a function `extract_text_from_pdf` that takes a PDF file path as input and returns all the text extracted from it."""

import fitz # PyMuPDF

def extract_text_from_pdf(pdf_path):
    """
    Extracts all text from a given PDF file.

    Args:
        pdf_path (str): The path to the PDF file.

    Returns:
        str: The extracted text from the PDF, or an empty string if an error occurs.
    """
    try:
        doc = fitz.open(pdf_path)
        text = ""
        for page_num in range(12,doc.page_count):
            page = doc.load_page(page_num)
            text += page.get_text()
        doc.close()
        return text
    except Exception as e:
        print(f"Error processing PDF {pdf_path}: {e}")
        return ""

"""Now, let's use the `extract_text_from_pdf` function to extract text from the `ncert-9-1-30.pdf` file and display the first 500 characters."""

pdf_file_path = '/content/ncert-9-1-30.pdf'
extracted_text = extract_text_from_pdf(pdf_file_path)

if extracted_text:
    print(extracted_text[:500])  # Print the first 500 characters of the extracted text
    print(f"\nTotal characters extracted: {len(extracted_text)}")
else:
    print(f"Failed to extract text from {pdf_file_path}")

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from collections import Counter
import re
stop_words = set(stopwords.words('english'))

words = re.findall(r'\b\w+\b', extracted_text.lower())


# Filter out stop words from the 'words' list
filtered_words = [word for word in words if word not in stop_words]

# Recalculate word frequencies for the filtered list
filtered_counter = Counter(filtered_words)

print("Top 30 most common words after removing stop words:")
print(filtered_counter.most_common(30))

def check_keywords(keywords):
  for word in keywords:
    count = filtered_words.count(word.lower()) # Ensure keyword is lowercase for comparison
    print(f"{word} -> {count}")

example_keywords = [
    "example", "illustration", "illustrate", "illustrated",
    "worked example", "case", "case study", "sample"
]

check_keywords(example_keywords)

question_keywords = [
    "exercise", "question", "questions", "problem",
    "problems", "q.", "q", "exercises", "solve",
    "evaluate", "find", "calculate", "explain",
    "define", "derive", "state"
]

check_keywords(question_keywords)

concept_keywords = [
    "is defined as", "refers to", "means", "definition",
    "called", "known as", "states that", "can be defined as"
]

check_keywords(concept_keywords)

law_keywords = [
    "law", "theorem", "principle", "rule",
    "newton", "archimedes", "ohm", "boyle"
]
check_keywords(law_keywords)

formula_keywords = [
    "=", "+", "-", "*", "/", "^",
    "equation", "formula", "calculate",
    "where", "given", "thus"
]

check_keywords(formula_keywords)

#Adding basic cleaning
def clean_text(text):
    text = re.sub(r'\n+', '\n', text)          # remove extra newlines
    text = re.sub(r'\s+', ' ', text)           # normalize spaces
    return text.strip()

# def split_into_blocks(text):
#     raw_blocks = text.split("\n\n")
#     final_blocks = []

#     for block in raw_blocks:
#         block = block.strip()

#         if not block:
#             continue

#         if "exercise" in block.lower():
#             lines = block.split("\n")
#             for line in lines:
#                 if line.strip():
#                     final_blocks.append(line.strip())
#         else:
#             final_blocks.append(block)

#     return final_blocks

def split_into_blocks(text):
    blocks = text.split("\n\n")

    cleaned_blocks = []
    for b in blocks:
        b = b.strip()
        if len(b) > 20:   # remove noise
            cleaned_blocks.append(b)

    return cleaned_blocks

import re

def normalize_block(text):
    print("STEP 1: ORIGINAL TEXT\n")
    print(text[:300])

    # Step 1: Remove multiple newlines
    text = re.sub(r'\n+', '\n', text)
    print("\nSTEP 2: AFTER REMOVING EXTRA NEWLINES\n")
    print(text[:300])

    # Step 2: Normalize spaces
    text = re.sub(r'\s+', ' ', text)
    print("\nSTEP 3: AFTER NORMALIZING SPACES\n")
    print(text[:300])

    return text.strip()

def split_into_blocks_new(text):
    lines = text.split("\n")

    blocks = []
    current_block = ""

    for line in lines:
        line = line.strip()

        if not line:
            continue

        # 🚨 Start new block if special keyword
        if line.lower().startswith(("example", "exercise", "question")):
            if current_block:
                blocks.append(current_block.strip())
            current_block = line

        # 🚨 Start new block if heading
        elif len(line) < 60 and line.isupper():
            if current_block:
                blocks.append(current_block.strip())
            blocks.append(line)
            current_block = ""

        # 🚨 Question lines
        elif line.startswith(("1.", "2.", "3.", "4.")):
            if current_block:
                blocks.append(current_block.strip())
            blocks.append(line)
            current_block = ""

        # ✅ Otherwise merge lines
        else:
            current_block += " " + line

    if current_block:
        blocks.append(current_block.strip())

    return blocks

# Splitting with single lossing meaning
# blocks = extracted_text.split("\n")
# blocks = extracted_text.split("\n\n")
blocks = extracted_text.split(" ")

# clean_blocks = [normalize_block(b) for b in blocks]
blocks = split_into_blocks_new(extracted_text)
blocks[100]



print("Toal blocks:", len(blocks))
for b in blocks[:20]:
    print(b)
    print("-----------------------------------------------------------------------------")

split_into_blocks(extracted_text)[:10][0]

def classify_block(text):
    t = text.lower().strip()

    if t.startswith(("1.", "2.", "3.", "q", "question")):
        return "question"

    if "example" in t or "illustration" in t:
        return "example"

    if "=" in t:
        return "formula"

    if len(t) < 60 and t.isupper():
        return "heading"

    return "concept"

def build_chunks_pipeline(raw_text):
    cleaned = clean_text(raw_text)

    blocks = split_into_blocks(cleaned)

    structured_blocks = []
    for b in blocks:
        structured_blocks.append({
            "text": b,
            "type": classify_block(b)
        })

    chunks = chunk_blocks(structured_blocks)

    return chunks

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2")

"""Hybrid Chunking (CORE PART 🔥)
🧠 Strategy
Preserve block meaning
Split only if too large
Add overlap
"""

def chunk_blocks(blocks, chunk_size=300, overlap=50):
    chunks = []

    for block in blocks:
        tokens = tokenizer.encode(block["text"])
        start = 0

        while start < len(tokens):
            end = start + chunk_size
            chunk_tokens = tokens[start:end]

            chunk_text = tokenizer.decode(chunk_tokens)

            chunks.append({
                "text": chunk_text,
                "type": block["type"]
            })

            start += chunk_size - overlap

    return chunks

chunks = build_chunks_pipeline(extracted_text)

print("Total chunks:", len(chunks))

for c in chunks[:50]:
    print("\nTYPE:", c["type"])
    print(c["text"][:200])