# -*- coding: utf-8 -*-
"""Ncert-MINI_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tVQ4XZmsA0Rz22faWh4BnOCB7w5DlrS

What We are Building

PDF → Clean Text → Chunks → BM25 → Top-k → LLM → Answer
"""

!pip install pymupdf

import fitz  # pymupdf

def extract_text_from_pdf(file_path):
    doc = fitz.open(file_path)
    full_text = ""

    for page_num in range(len(doc)):
        page = doc[page_num]
        text = page.get_text()
        full_text += text + "\n"

    return full_text


# Example
pdf_path = "ncert-9-1-30.pdf"
text = extract_text_from_pdf(pdf_path)

print(text[1000:10000])  # preview

"""I can read paragraphs, questions are visible, examples are visible"""

sample_text = """
Motion is the change in position of an object with respect to time.

Example: A car moving along a straight road at a constant speed of 20 m/s.

Force is defined as push or pull acting on an object.

Example: Applying force to push a box across the floor.

Newton's Second Law states that Force = mass × acceleration (F = ma).

Example: A 2 kg object accelerating at 3 m/s^2 will experience a force of 6 N.

Exercise Questions:
1. What is motion?
2. Define force.
3. Explain Newton's Second Law.
4. Calculate force when mass is 5 kg and acceleration is 2 m/s^2.
"""

def split_into_blocks(text):
    blocks = text.split("\n\n")
    cleaned_blocks = []

    for block in blocks:
        block = block.strip()
        if block:
            cleaned_blocks.append(block)

    return cleaned_blocks


blocks = split_into_blocks(sample_text)

for i, b in enumerate(blocks):
    print(f"\nBlock {i+1}: {b}")

def classify_block(block):
    lower = block.lower()

    if "example" in lower:
        return "example"
    elif "question" in lower or "exercise" in lower:
        return "question"
    else:
        return "concept"


structured_blocks = []

for block in blocks:
    structured_blocks.append({
        "text": block,
        "type": classify_block(block)
    })


for item in structured_blocks:
    print(item)

from transformers import AutoTokenizer

gpt2_tokenizer = AutoTokenizer.from_pretrained("gpt2")

sample = structured_blocks[0]["text"]

tokens = gpt2_tokenizer.tokenize(sample)

print("Text:", sample)
print("\nTokens:", tokens)
print("\nToken count:", len(tokens))

chunks = []

for item in structured_blocks:
    chunks.append({
        "text": item["text"],
        "type": item["type"]
    })

print("Total chunks:", len(chunks))

for c in chunks:
    print(c)

!pip install rank_bm25

from rank_bm25 import BM25Okapi

# Convert chunks into tokenized format
corpus = [chunk["text"] for chunk in chunks]

tokenized_corpus = [doc.lower().split() for doc in corpus]

# Initialize BM25
bm25 = BM25Okapi(tokenized_corpus)

def retrieve(query, top_k=3):
    tokenized_query = query.lower().split()

    scores = bm25.get_scores(tokenized_query)

    # Get top results
    ranked_indices = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)

    top_chunks = [chunks[i] for i in ranked_indices[:top_k]]

    return top_chunks

queries = [
    # "What is motion?",
    # "Define force",
    # "Explain Newton's second law",
    # "What is gravity?",
    "Motion is change in"
]

for q in queries:
    print("\nQuery:", q)
    results = retrieve(q)

    for r in results:
        print("->", r["text"])

def debug_retrieve(query):
    tokenized_query = query.lower().split()
    scores = bm25.get_scores(tokenized_query)

    for i, score in enumerate(scores):
        print(f"Chunk {i} | Score: {score}")
        print(chunks[i]["text"])
        print("-"*50)